name: stack
version: '1.6.0'
synopsis: The Haskell Tool Stack
description: ! 'Please see the README.md for usage information, and
  the wiki on Github for more details.  Also, note that
  the API for the library is not currently stable, and may
  change significantly, even between minor releases. It is
  currently only intended for use by the executable.'
category: Development
author: Commercial Haskell SIG
maintainer: manny@fpcomplete.com
license: BSD3
github: commercialhaskell/stack.git
homepage: http://haskellstack.org
custom-setup:
  dependencies:
  - base
  - Cabal >= 2.0
  - filepath
extra-source-files:
- CONTRIBUTING.md
- ChangeLog.md
- README.md
- doc/*.md
- src/setup-shim/StackSetupShim.hs
- test/package-dump/ghc-7.8.txt
- test/package-dump/ghc-7.8.4-osx.txt
- test/package-dump/ghc-7.10.txt
- stack.yaml
ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
dependencies:
- Cabal >=2.0
- aeson >=1.0
- annotated-wl-pprint
- ansi-terminal >=0.6.2.3
- async
- attoparsec >=0.12.1.5
- base >=4.9 && < 5
- base64-bytestring
- blaze-builder
- bytestring >=0.10.4.0
- clock >=0.7.2
- conduit >=1.2.8
- conduit-extra >=1.1.14
- containers >=0.5.5.1
- cryptonite >=0.19
- cryptonite-conduit >=0.1
- deepseq >=1.4
- directory >=1.2.1.0
- echo >=0.1.3
- exceptions >=0.8.0.2
- extra >=1.4.10
- fast-logger >=2.3.1
- file-embed >=0.0.10
- filelock >=0.1.0.1
- filepath >=1.3.0.2
- fsnotify >=0.2.1
- generic-deriving >=1.10.5
- hackage-security
- hashable >=1.2.3.2
- hastache
- hpack >=0.17.0
- hpc >=0.6.0.2
- http-client >=0.5.3.3
- http-client-tls >=0.3.4
- http-conduit >=2.2.3
- http-types >=0.8.6 && <0.10
- memory >=0.13
- microlens >=0.3.0.0
- microlens-mtl >=0.1.10.0
- mintty >=0.1.1
- monad-logger >=0.3.25
- mono-traversable >=0.10.2
- mtl >=2.1.3.1
- neat-interpolation >=0.3
- network-uri
- open-browser >=0.2.1
- optparse-applicative >=0.13
- path >=0.6
- path-io >=1.1.0
- persistent >=2.1.2
- persistent-sqlite (>=2.1.4 && <2.5.0.1) || >2.5.0.1
- persistent-template >=2.1.1
- pretty >=1.1.1.1
- primitive
- process >=1.2.1.0
- project-template >=0.2
- regex-applicative-text >=0.1.0.1
- resourcet >=1.1.4.1
- retry >=0.6
- semigroups >=0.5
- split
- stm >=2.4.4
- store >=0.4.1
- store-core >=0.4
- streaming-commons >=0.1.10.0
- tar >=0.5.0.3
- template-haskell >=2.9.0.0
- temporary >=1.2.0.3
- text >=1.2.0.4
- text-metrics >=0.3
- th-reify-many >=0.1.6
- time >=1.5
- tls >=1.3.8
- transformers >=0.3.0.0
- unicode-transforms >=0.1
- unix-compat >=0.4.1.4
- unliftio
- unordered-containers >=0.2.5.1
- vector >=0.10.12.3
- yaml >=0.8.20
- zip-archive >=0.2.3.7
- zlib >=0.5.4.2
when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32
  else:
    build-tools:
    - hsc2hs >=0.68
    dependencies:
    - unix >=2.7.0.1
    - pid1 >=0.1
    - bindings-uname >=0.1
library:
  source-dirs: src/
  ghc-options:
  - -fwarn-identities
executables:
  stack:
    main: Main.hs
    source-dirs: src/main
    ghc-options:
    - -threaded
    dependencies:
    - stack
    other-modules:
    - Paths_stack
    when:
    - condition: flag(static)
      ld-options:
      - -static
      - -pthread
    - condition: ! '!(flag(disable-git-info))'
      cpp-options: -DUSE_GIT_INFO
      dependencies:
      - gitrev >=1.1
      - optparse-simple >=0.0.3
    - condition: flag(hide-dependency-versions)
      cpp-options: -DHIDE_DEP_VERSIONS
tests:
  stack-test:
    main: Test.hs
    source-dirs: src/test
    ghc-options:
    - -threaded
    dependencies:
    - QuickCheck >=2.8.2
    - hspec >=2.2
    - stack
    - smallcheck
  stack-integration-test:
    main: IntegrationSpec.hs
    source-dirs:
    - test/integration
    - test/integration/lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >=2.2
    when:
    - condition: ! '!(flag(integration-tests))'
      buildable: false
flags:
  static:
    description: Pass -static/-pthread to ghc when linking the stack binary.
    manual: true
    default: false
  disable-git-info:
    description: Disable compile-time inclusion of current git info in stack
    manual: true
    default: false
  hide-dependency-versions:
    description: Hides dependency versions from "stack --version", used only by building
      with stack.yaml
    manual: true
    default: false
  integration-tests:
    description: Run the integration test suite
    manual: true
    default: false
